server:
  port: 8003
spring:
  application:
    name: j-cloud-consumer-fegin-hystrix

# eureka 配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://jorian:123456@localhost:8761/eureka
logging:
  level:
    root: INFO
